apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deployment
  namespace: bookstore-ns
spec:
  selector:
    matchLabels:
      app: book
  replicas: 1
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: book
          image: kevin0988/books_backend:latest
          ports:
            - containerPort: 80
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - book