apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  namespace: bookstore-ns
spec:
  selector:
    matchLabels:
      app: customer
  replicas: 2
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: kevin0988/customers_backend:latest
          ports:
            - containerPort: 80
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - customer

